// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientRequestProtocol.proto

package iie.logcabin.clustercontroller.protocol;

public final class ClientRequestProtocolBuf {
  private ClientRequestProtocolBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientRequestProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string transportProtocol = 1;
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    boolean hasTransportProtocol();
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    java.lang.String getTransportProtocol();
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    com.google.protobuf.ByteString
        getTransportProtocolBytes();

    // required string channelName = 2;
    /**
     * <code>required string channelName = 2;</code>
     */
    boolean hasChannelName();
    /**
     * <code>required string channelName = 2;</code>
     */
    java.lang.String getChannelName();
    /**
     * <code>required string channelName = 2;</code>
     */
    com.google.protobuf.ByteString
        getChannelNameBytes();

    // required string requestType = 3;
    /**
     * <code>required string requestType = 3;</code>
     */
    boolean hasRequestType();
    /**
     * <code>required string requestType = 3;</code>
     */
    java.lang.String getRequestType();
    /**
     * <code>required string requestType = 3;</code>
     */
    com.google.protobuf.ByteString
        getRequestTypeBytes();
  }
  /**
   * Protobuf type {@code iie.logcabin.clustercontroller.protocol.ClientRequestProtocol}
   */
  public static final class ClientRequestProtocol extends
      com.google.protobuf.GeneratedMessage
      implements ClientRequestProtocolOrBuilder {
    // Use ClientRequestProtocol.newBuilder() to construct.
    private ClientRequestProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientRequestProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientRequestProtocol defaultInstance;
    public static ClientRequestProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public ClientRequestProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientRequestProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              transportProtocol_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              channelName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requestType_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol.class, iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientRequestProtocol> PARSER =
        new com.google.protobuf.AbstractParser<ClientRequestProtocol>() {
      public ClientRequestProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientRequestProtocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientRequestProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string transportProtocol = 1;
    public static final int TRANSPORTPROTOCOL_FIELD_NUMBER = 1;
    private java.lang.Object transportProtocol_;
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    public boolean hasTransportProtocol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    public java.lang.String getTransportProtocol() {
      java.lang.Object ref = transportProtocol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transportProtocol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTransportProtocolBytes() {
      java.lang.Object ref = transportProtocol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportProtocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string channelName = 2;
    public static final int CHANNELNAME_FIELD_NUMBER = 2;
    private java.lang.Object channelName_;
    /**
     * <code>required string channelName = 2;</code>
     */
    public boolean hasChannelName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string channelName = 2;</code>
     */
    public java.lang.String getChannelName() {
      java.lang.Object ref = channelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string channelName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getChannelNameBytes() {
      java.lang.Object ref = channelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string requestType = 3;
    public static final int REQUESTTYPE_FIELD_NUMBER = 3;
    private java.lang.Object requestType_;
    /**
     * <code>required string requestType = 3;</code>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string requestType = 3;</code>
     */
    public java.lang.String getRequestType() {
      java.lang.Object ref = requestType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requestType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRequestTypeBytes() {
      java.lang.Object ref = requestType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      transportProtocol_ = "";
      channelName_ = "";
      requestType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTransportProtocol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannelName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTransportProtocolBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getChannelNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRequestTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTransportProtocolBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getChannelNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRequestTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iie.logcabin.clustercontroller.protocol.ClientRequestProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol.class, iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol.Builder.class);
      }

      // Construct using iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transportProtocol_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        channelName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_descriptor;
      }

      public iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol getDefaultInstanceForType() {
        return iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol.getDefaultInstance();
      }

      public iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol build() {
        iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol buildPartial() {
        iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol result = new iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transportProtocol_ = transportProtocol_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channelName_ = channelName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestType_ = requestType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol) {
          return mergeFrom((iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol other) {
        if (other == iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol.getDefaultInstance()) return this;
        if (other.hasTransportProtocol()) {
          bitField0_ |= 0x00000001;
          transportProtocol_ = other.transportProtocol_;
          onChanged();
        }
        if (other.hasChannelName()) {
          bitField0_ |= 0x00000002;
          channelName_ = other.channelName_;
          onChanged();
        }
        if (other.hasRequestType()) {
          bitField0_ |= 0x00000004;
          requestType_ = other.requestType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransportProtocol()) {
          
          return false;
        }
        if (!hasChannelName()) {
          
          return false;
        }
        if (!hasRequestType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iie.logcabin.clustercontroller.protocol.ClientRequestProtocolBuf.ClientRequestProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string transportProtocol = 1;
      private java.lang.Object transportProtocol_ = "";
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public boolean hasTransportProtocol() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public java.lang.String getTransportProtocol() {
        java.lang.Object ref = transportProtocol_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          transportProtocol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTransportProtocolBytes() {
        java.lang.Object ref = transportProtocol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transportProtocol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public Builder setTransportProtocol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transportProtocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public Builder clearTransportProtocol() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transportProtocol_ = getDefaultInstance().getTransportProtocol();
        onChanged();
        return this;
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public Builder setTransportProtocolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transportProtocol_ = value;
        onChanged();
        return this;
      }

      // required string channelName = 2;
      private java.lang.Object channelName_ = "";
      /**
       * <code>required string channelName = 2;</code>
       */
      public boolean hasChannelName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string channelName = 2;</code>
       */
      public java.lang.String getChannelName() {
        java.lang.Object ref = channelName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          channelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string channelName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getChannelNameBytes() {
        java.lang.Object ref = channelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string channelName = 2;</code>
       */
      public Builder setChannelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        channelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string channelName = 2;</code>
       */
      public Builder clearChannelName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channelName_ = getDefaultInstance().getChannelName();
        onChanged();
        return this;
      }
      /**
       * <code>required string channelName = 2;</code>
       */
      public Builder setChannelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        channelName_ = value;
        onChanged();
        return this;
      }

      // required string requestType = 3;
      private java.lang.Object requestType_ = "";
      /**
       * <code>required string requestType = 3;</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string requestType = 3;</code>
       */
      public java.lang.String getRequestType() {
        java.lang.Object ref = requestType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string requestType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRequestTypeBytes() {
        java.lang.Object ref = requestType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requestType = 3;</code>
       */
      public Builder setRequestType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requestType = 3;</code>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestType_ = getDefaultInstance().getRequestType();
        onChanged();
        return this;
      }
      /**
       * <code>required string requestType = 3;</code>
       */
      public Builder setRequestTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:iie.logcabin.clustercontroller.protocol.ClientRequestProtocol)
    }

    static {
      defaultInstance = new ClientRequestProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:iie.logcabin.clustercontroller.protocol.ClientRequestProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ClientRequestProtocol.proto\022\'iie.logca" +
      "bin.clustercontroller.protocol\"\\\n\025Client" +
      "RequestProtocol\022\031\n\021transportProtocol\030\001 \002" +
      "(\t\022\023\n\013channelName\030\002 \002(\t\022\023\n\013requestType\030\003" +
      " \002(\tBC\n\'iie.logcabin.clustercontroller.p" +
      "rotocolB\030ClientRequestProtocolBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_iie_logcabin_clustercontroller_protocol_ClientRequestProtocol_descriptor,
              new java.lang.String[] { "TransportProtocol", "ChannelName", "RequestType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
