// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerResponseProtocol.proto

package iie.logcabin.clustercontroller.protocol;

public final class ServerResponseProtocolBuf {
  private ServerResponseProtocolBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerResponseProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string transportProtocol = 1;
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    boolean hasTransportProtocol();
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    java.lang.String getTransportProtocol();
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    com.google.protobuf.ByteString
        getTransportProtocolBytes();

    // required string transportUrl = 2;
    /**
     * <code>required string transportUrl = 2;</code>
     */
    boolean hasTransportUrl();
    /**
     * <code>required string transportUrl = 2;</code>
     */
    java.lang.String getTransportUrl();
    /**
     * <code>required string transportUrl = 2;</code>
     */
    com.google.protobuf.ByteString
        getTransportUrlBytes();
  }
  /**
   * Protobuf type {@code iie.logcabin.clustercontroller.protocol.ServerResponseProtocol}
   */
  public static final class ServerResponseProtocol extends
      com.google.protobuf.GeneratedMessage
      implements ServerResponseProtocolOrBuilder {
    // Use ServerResponseProtocol.newBuilder() to construct.
    private ServerResponseProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerResponseProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerResponseProtocol defaultInstance;
    public static ServerResponseProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public ServerResponseProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerResponseProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              transportProtocol_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              transportUrl_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol.class, iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerResponseProtocol> PARSER =
        new com.google.protobuf.AbstractParser<ServerResponseProtocol>() {
      public ServerResponseProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerResponseProtocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerResponseProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string transportProtocol = 1;
    public static final int TRANSPORTPROTOCOL_FIELD_NUMBER = 1;
    private java.lang.Object transportProtocol_;
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    public boolean hasTransportProtocol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    public java.lang.String getTransportProtocol() {
      java.lang.Object ref = transportProtocol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transportProtocol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transportProtocol = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTransportProtocolBytes() {
      java.lang.Object ref = transportProtocol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportProtocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string transportUrl = 2;
    public static final int TRANSPORTURL_FIELD_NUMBER = 2;
    private java.lang.Object transportUrl_;
    /**
     * <code>required string transportUrl = 2;</code>
     */
    public boolean hasTransportUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string transportUrl = 2;</code>
     */
    public java.lang.String getTransportUrl() {
      java.lang.Object ref = transportUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transportUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transportUrl = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTransportUrlBytes() {
      java.lang.Object ref = transportUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      transportProtocol_ = "";
      transportUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTransportProtocol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransportUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTransportProtocolBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTransportUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTransportProtocolBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTransportUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iie.logcabin.clustercontroller.protocol.ServerResponseProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol.class, iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol.Builder.class);
      }

      // Construct using iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transportProtocol_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        transportUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_descriptor;
      }

      public iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol getDefaultInstanceForType() {
        return iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol.getDefaultInstance();
      }

      public iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol build() {
        iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol buildPartial() {
        iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol result = new iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transportProtocol_ = transportProtocol_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.transportUrl_ = transportUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol) {
          return mergeFrom((iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol other) {
        if (other == iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol.getDefaultInstance()) return this;
        if (other.hasTransportProtocol()) {
          bitField0_ |= 0x00000001;
          transportProtocol_ = other.transportProtocol_;
          onChanged();
        }
        if (other.hasTransportUrl()) {
          bitField0_ |= 0x00000002;
          transportUrl_ = other.transportUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransportProtocol()) {
          
          return false;
        }
        if (!hasTransportUrl()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iie.logcabin.clustercontroller.protocol.ServerResponseProtocolBuf.ServerResponseProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string transportProtocol = 1;
      private java.lang.Object transportProtocol_ = "";
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public boolean hasTransportProtocol() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public java.lang.String getTransportProtocol() {
        java.lang.Object ref = transportProtocol_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          transportProtocol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTransportProtocolBytes() {
        java.lang.Object ref = transportProtocol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transportProtocol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public Builder setTransportProtocol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transportProtocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public Builder clearTransportProtocol() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transportProtocol_ = getDefaultInstance().getTransportProtocol();
        onChanged();
        return this;
      }
      /**
       * <code>required string transportProtocol = 1;</code>
       */
      public Builder setTransportProtocolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transportProtocol_ = value;
        onChanged();
        return this;
      }

      // required string transportUrl = 2;
      private java.lang.Object transportUrl_ = "";
      /**
       * <code>required string transportUrl = 2;</code>
       */
      public boolean hasTransportUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string transportUrl = 2;</code>
       */
      public java.lang.String getTransportUrl() {
        java.lang.Object ref = transportUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          transportUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transportUrl = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTransportUrlBytes() {
        java.lang.Object ref = transportUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transportUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transportUrl = 2;</code>
       */
      public Builder setTransportUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        transportUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transportUrl = 2;</code>
       */
      public Builder clearTransportUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        transportUrl_ = getDefaultInstance().getTransportUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string transportUrl = 2;</code>
       */
      public Builder setTransportUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        transportUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:iie.logcabin.clustercontroller.protocol.ServerResponseProtocol)
    }

    static {
      defaultInstance = new ServerResponseProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:iie.logcabin.clustercontroller.protocol.ServerResponseProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ServerResponseProtocol.proto\022\'iie.logc" +
      "abin.clustercontroller.protocol\"I\n\026Serve" +
      "rResponseProtocol\022\031\n\021transportProtocol\030\001" +
      " \002(\t\022\024\n\014transportUrl\030\002 \002(\tBD\n\'iie.logcab" +
      "in.clustercontroller.protocolB\031ServerRes" +
      "ponseProtocolBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_iie_logcabin_clustercontroller_protocol_ServerResponseProtocol_descriptor,
              new java.lang.String[] { "TransportProtocol", "TransportUrl", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
